# Generated by Django 5.1.5 on 2026-01-22 22:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='MonitorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('vatican', 'Vatican Museums'), ('colosseum', 'Colosseum')], max_length=50)),
                ('area_name', models.CharField(help_text='e.g., Musei Vaticani or Colosseo', max_length=255)),
                ('dates', models.JSONField(help_text="List of dates to check (e.g., ['2026-06-15'])")),
                ('preferred_times', models.JSONField(help_text="List of preferred times (e.g., ['10:00', '14:30'])")),
                ('visitors', models.PositiveIntegerField(default=1)),
                ('ticket_type', models.IntegerField(choices=[(0, 'Regular Ticket'), (1, 'Guided Tour')], default=0)),
                ('language', models.CharField(default='English', max_length=50)),
                ('match_strategy', models.CharField(choices=[('any', 'ANY (Notify if any slot matches)'), ('all', 'ALL (Notify only if all slots match)')], default='any', max_length=20)),
                ('notification_mode', models.CharField(choices=[('any_change', 'Notify on any change'), ('available_only', 'Notify only when available'), ('silent', 'Silent (No notifications)')], default='any_change', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='unknown', max_length=50)),
                ('last_result_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='monitors.agency')),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitors.monitortask')),
            ],
        ),
    ]
