# Generated by Django 5.1.5 on 2026-01-23 12:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_proxy_sitecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
