# Generated by Django 5.1.5 on 2026-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_agency_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='check_interval',
            field=models.IntegerField(default=60, help_text='Interval in seconds'),
        ),
    ]
