
# Generated by Django 5.1.5 on 2026-01-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_monitortask_check_interval'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='agency',
                    name='owner_id',
                    field=models.CharField(blank=True, db_index=True, help_text='Clerk User ID', max_length=100, null=True, unique=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    # SQLite doesn't support IF NOT EXISTS in ADD COLUMN
                    # We can skip this check for SQLite or use a more complex logic,
                    # but simpler is to just assume it might fail if exists (which Django handles gracefully usually)
                    # or better, just use standard Django AddField for new columns if we don't need raw SQL speed
                    # But since this is a migration file we can't easily change the logic type now without breaking history.
                    # FIX: Remove IF NOT EXISTS for SQLite compatibility or handle it via Python
                    # For now, let's try standard SQL which works on Postgres but fails on SQLite.
                    # Since we are likely on SQLite locally, we need a compatible statement.
                    # SQLite supports ADD COLUMN but not IF NOT EXISTS.
                    'ALTER TABLE monitors_agency ADD COLUMN owner_id varchar(100);',
                    reverse_sql='ALTER TABLE monitors_agency DROP COLUMN owner_id;'
                ),
                # Unique constraint adding in SQLite is tricky, usually requires recreation of table.
                # But modern SQLite supports CREATE UNIQUE INDEX.
                migrations.RunSQL(
                    'CREATE UNIQUE INDEX IF NOT EXISTS monitors_agency_owner_id_key ON monitors_agency(owner_id);',
                    reverse_sql='DROP INDEX IF EXISTS monitors_agency_owner_id_key;'
                ),
            ],
        ),
        migrations.AddField(
            model_name='proxy',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proxy',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
