
# Generated by Django 5.1.5 on 2026-01-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_monitortask_check_interval'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='agency',
                    name='owner_id',
                    field=models.CharField(blank=True, db_index=True, help_text='Clerk User ID', max_length=100, null=True, unique=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE monitors_agency ADD COLUMN IF NOT EXISTS owner_id varchar(100);',
                    reverse_sql='ALTER TABLE monitors_agency DROP COLUMN IF EXISTS owner_id;'
                ),
                migrations.RunSQL(
                    'ALTER TABLE monitors_agency ADD CONSTRAINT monitors_agency_owner_id_key UNIQUE (owner_id);',
                    reverse_sql='ALTER TABLE monitors_agency DROP CONSTRAINT monitors_agency_owner_id_key;'
                ),
            ],
        ),
        migrations.AddField(
            model_name='proxy',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proxy',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
