# Generated by Django 5.1.5 on 2026-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0005_agency_owner_id_proxy_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('agency', 'Agency')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='ticket_id',
            field=models.CharField(blank=True, db_index=True, help_text="Vatican ticket ID (e.g., '929041748' from resolve_all_dynamic_ids). Leave empty to scan ALL tickets.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='ticket_label',
            field=models.CharField(blank=True, help_text="e.g. 'Standard Entry (Full Price)'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='ticket_name',
            field=models.CharField(blank=True, help_text="Human-readable ticket name (e.g., 'Musei Vaticani - Biglietti d'ingresso')", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='tier',
            field=models.CharField(choices=[('monitor', 'Monitor (Notify Only)'), ('sniper', 'Sniper (Auto-Book)')], default='monitor', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='language',
            field=models.CharField(blank=True, help_text="Language code for guided tours: ENG, ITA, FRA, DEU, SPA. NULL for standard tickets that don't require language.", max_length=10, null=True),
        ),
    ]
