# Generated by Django 6.0.3 on 2026-03-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0007_fix_owner_id_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortask',
            name='language',
            field=models.CharField(blank=True, help_text="Language code for guided tours: ENG, ITA, FRA, TED, SPA. NULL for standard tickets that don't require language.", max_length=10, null=True),
        ),
    ]
