# Generated by Django 5.1.5 on 2026-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0009_alter_monitortask_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortask',
            name='site',
            field=models.CharField(choices=[('vatican', 'Vatican Museums')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecredential',
            name='site',
            field=models.CharField(choices=[('vatican', 'Vatican')], max_length=50),
        ),
    ]
