# Generated by Django 6.0.3 on 2026-03-10 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0010_alter_monitortask_site_alter_sitecredential_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('chat_type', models.CharField(max_length=20)),
                ('chat_title', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_username', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('added_by_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('added_by_username', models.CharField(blank=True, max_length=255, null=True)),
                ('added_by_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_count', models.IntegerField(blank=True, null=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('notification_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_groups', to='monitors.agency')),
            ],
            options={
                'db_table': 'telegram_groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
