# Generated by Django 6.0.3 on 2026-03-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0013_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
