# Generated by Django 6.0.3 on 2026-04-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0018_heldslot_recap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heldslot',
            name='jsessionid',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DynamicInjectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_overrides', models.JSONField(default=list, help_text="JSON list of participant objects: [{'first_name': 'John', 'last_name': 'Doe'}, ...]")),
                ('card_overrides', models.JSONField(default=dict, help_text="JSON object with card details: {'number': '4111...', 'expiry': '12/2026', 'cvv': '123', 'holder': 'Name'}")),
                ('action', models.CharField(choices=[('epay', 'Generate Epay URL'), ('snipe', 'Direct Snipe with Payment')], default='epay', max_length=10)),
                ('expires_at', models.DateTimeField(help_text='When this injection configuration expires')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this config has been used')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('result_epay_url', models.TextField(blank=True, help_text="Generated epay URL if action='epay'", null=True)),
                ('result_snipe_status', models.CharField(blank=True, help_text="Snipe result status if action='snipe'", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_configs', to='monitors.buyerprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_configs', to='monitors.monitortask')),
            ],
            options={
                'db_table': 'dynamic_injection_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
