# Generated by Django 4.2.7 on 2026-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0019_alter_heldslot_jsessionid_dynamicinjectionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='participants_json',
            field=models.TextField(blank=True, help_text='Participant names for snipe reservation (JSON list)', null=True),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='pay_mode',
            field=models.CharField(choices=[('link', 'Send payment link (user pays themselves)'), ('auto', 'Auto-pay with stored card')], default='link', help_text="snipe tier only: 'link' sends payment URL to Telegram, 'auto' pays with stored card", max_length=10),
        ),
    ]
