# Generated by Django 4.2.7 on 2026-04-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0020_add_pay_mode_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkHoldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(help_text='Start date (inclusive)')),
                ('date_to', models.DateField(help_text='End date (inclusive)')),
                ('time_from', models.CharField(default='08:00', help_text='HH:MM', max_length=5)),
                ('time_to', models.CharField(default='17:00', help_text='HH:MM', max_length=5)),
                ('visitors', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_locked', models.IntegerField(default=0)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_hold_configs', to='monitors.agency')),
            ],
            options={
                'db_table': 'bulk_hold_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DynamicInjectionConfig',
        ),
    ]
