# Generated by Django 4.2.7 on 2026-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0021_add_bulk_hold_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='checkout_method',
            field=models.CharField(choices=[('api', 'API reservation (needs 2captcha token)'), ('playwright', 'Playwright UI (no 2captcha, slower)')], default='api', help_text="'api' = fast (needs 2captcha), 'playwright' = slow but free (no token needed)", max_length=12),
        ),
    ]
