# Generated by Django 6.0.3 on 2026-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0022_add_checkout_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkholdconfig',
            name='adult_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bulkholdconfig',
            name='child_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heldslot',
            name='adult_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='heldslot',
            name='child_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='adult_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='child_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
