# Generated by Django 4.2.7 on 2026-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0023_bulkholdconfig_adult_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heldslot',
            name='payment_ready',
            field=models.BooleanField(default=False, help_text='User clicked Pay in Telegram, signal the worker to break hold and proceed.'),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='remote_worker_claimed',
            field=models.DateTimeField(blank=True, help_text='Timestamp when a remote worker started this task.', null=True),
        ),
        migrations.AddField(
            model_name='monitortask',
            name='remote_worker_needed',
            field=models.BooleanField(default=False, help_text='Set to True if this task should be handled by a remote Windows browser node instead of internal API.'),
        ),
    ]
