# Generated by Django 4.2.7 on 2026-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0024_heldslot_payment_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='agent_target',
            field=models.CharField(blank=True, help_text="Specific agent ID to open Chrome on (e.g. 'windows-main'). NULL = any available agent.", max_length=100, null=True),
        ),
    ]
