# Generated by Django 6.0.3 on 2026-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0025_monitortask_agent_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkholdconfig',
            name='target_total',
            field=models.PositiveIntegerField(default=10, help_text='Goal: total tickets to hold across all slots'),
        ),
    ]
