# Generated by Django 4.2.7 on 2026-05-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0026_add_target_total_to_bulkhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='google_sheet_url',
            field=models.CharField(blank=True, help_text='Google Sheets URL for participant names', max_length=500, null=True),
        ),
    ]
