# Generated by Django 4.2.7 on 2026-05-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0027_add_google_sheet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitortask',
            name='agent_target',
        ),
        migrations.RemoveField(
            model_name='monitortask',
            name='checkout_method',
        ),
        migrations.RemoveField(
            model_name='monitortask',
            name='pay_mode',
        ),
        migrations.RemoveField(
            model_name='monitortask',
            name='remote_worker_claimed',
        ),
        migrations.RemoveField(
            model_name='monitortask',
            name='remote_worker_needed',
        ),
    ]
