import asyncio
import logging
import sys
from playwright.async_api import async_playwright
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("DebugIDs")

async def main():
    logger.info("🚀 Starting ID Discovery for Feb 13...")
    
    # URL for Guided Tours Feb 13 (Calculated previously)
    # Timestamp: 1770937200000 (Midnight Rome for Feb 13)
    # Tag: MV-Visite-Guidate
    # URL: https://tickets.museivaticani.va/home/fromtag/1/1770937200000/MV-Visite-Guidate/1
    # WAIT! The user provided URL in previous turn had timestamp 1769727600000 for "Guided" (Jan 30?? No wait, previous turn analysis said 1769... was Jan 30/29 UTC).
    # Let's use the one generated by the Valid Bot Logic (verify_feb13.py log said it resolved ID 132704452 from SOME url).
    # The verify script used the bot's internal logic.
    # I will replicate the bot's logic to generate the URL dynamically to be sure.
    
    # Recalculate Timestamp correctly
    from datetime import datetime
    try:
         from zoneinfo import ZoneInfo
    except:
         from dateutil.tz import gettz as ZoneInfo

    target_date = "13/02/2026"
    dt = datetime.strptime(target_date, "%d/%m/%Y")
    rome = ZoneInfo("Europe/Rome")
    midnight = dt.replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=rome)
    ts = int(midnight.timestamp() * 1000)
    
    url = f"https://tickets.museivaticani.va/home/fromtag/1/{ts}/MV-Visite-Guidate/1"
    
    logger.info(f"🕸️ Target URL: {url}")

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()
        
        await page.goto(url, timeout=60000)
        await page.wait_for_timeout(5000)
        
        # Find ALL buttons with data-cy bookTicket
        buttons = page.locator("[data-cy^='bookTicket_']")
        count = await buttons.count()
        logger.info(f"🔢 Found {count} 'Book' buttons on the page.")
        
        if count == 0:
            logger.warning("❌ No buttons found! Page might be empty?")
            # Screenshot
            await page.screenshot(path="/app/debug_no_buttons.png")
        
        for i in range(count):
            btn = buttons.nth(i)
            data_cy = await btn.get_attribute("data-cy")
            
            # Try to get context/text (Parent of parent usually has the title)
            # Or just the card text
            card = btn.locator("xpath=./ancestor::div[contains(@class, 'card')]").first
            card_text = "N/A"
            if await card.count() > 0:
                 card_text = await card.inner_text()
                 card_text = card_text.replace("\n", " | ")
            else:
                 # Fallback: Parent text
                 parent = btn.locator("xpath=..")
                 card_text = await parent.inner_text()
                 card_text = card_text.replace("\n", " | ")
            
            # Explicitly check for ID
            logger.info(f"🔹 Item {i+1}: ID={data_cy} | Text: {card_text.strip()}")
            
        await browser.close()
        
if __name__ == "__main__":
    asyncio.run(main())
